export const GET_CURRENT_LOCATION_SUCCESS = 'GET_CURRENT_LOCATION_SUCCESS';
export const GET_CURRENT_LOCATION_REQUEST = 'GET_CURRENT_LOCATION_REQUEST';

export const GET_PICKUP_LOCATION = 'GET_PICKUP_LOCATION';
export const GET_DROPOFF_LOCATION = 'GET_DROPOFF_LOCATION';